version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx_main
        ports:
            - "9121:8000"
        volumes:
            - .:/usr/src/app
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - web

    web: &web
        build: .
        command: /django_start
        container_name: django_main
        depends_on:
            - db1
        volumes:
            - .:/usr/src/app
        ports:
            - "8010:8000"

    db1:
        image: postgres:latest
        container_name: db_main
        env_file:
            - ./.envs/.env
        volumes:
            - ./db_dumps:/usr/src/db_dumps
        ports:
            - 54324:5432
        expose:
            - "5432"

